# Configuration de production pour les routes de sécurité
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
