services:
  - type: web
    name: bibliotheque-enfant
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: APP_SECRET
        generateValue: true
      - key: MAILER_DSN
        value: null://null
    healthCheckPath: /
    autoDeploy: true
