framework:
    asset_mapper:
        # Configuration de production pour Asset Mapper
        paths:
            - assets/
        exclude:
            - '*.map'
            - '*.d.ts'
        importmap_polyfill: auto
        # Désactiver la compilation automatique en production
        compile: false
