framework:
    asset_mapper:
        # Configuration de production pour Asset Mapper
        paths:
            - assets/
        excluded_patterns:
            - '*.map'
            - '*.d.ts'
        importmap_polyfill: false
        missing_import_mode: warn
