framework:
    cache:
        # Configuration de production pour le cache
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.project_dir%/var/cache'
        
        # Configuration des pools de cache
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
