framework:
    cache:
        # Configuration de production pour le cache
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.project_dir%/var/cache'
        default_doctrine_provider: 'doctrine.system_cache_pool'
        
        # Configuration des pools de cache
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
                tags: cache.tags
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
                tags: cache.tags
