doctrine:
    dbal:
        # Configuration de production pour PostgreSQL
        driver: pdo_pgsql
        charset: utf8
        
    orm:
        # Configuration de production
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
