doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '15'
        profiling_collect_backtrace: false
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
