framework:
    # Configuration de production pour Render
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.project_dir%/var/cache'
        default_doctrine_provider: 'doctrine.system_cache_pool'
    
    # Désactiver le debug en production
    debug: false
    
    # Configuration des sessions
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    # Configuration des assets
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
    
    # Configuration de la sécurité
    security:
        # Désactiver le profiler en production
        enable_authenticator_manager: true
    
    # Configuration des logs
    log:
        # Utiliser stderr pour les logs en production
        handlers:
            main:
                type: stream
                path: 'php://stderr'
                level: error
