monolog:
    # Configuration de production pour Monolog
    handlers:
        # Log principal en production
        main:
            type: stream
            path: 'php://stderr'
            level: error
