# Configuration de production pour les routes
# Ce fichier définit les routes de l'application

# Routes d'administration (EasyAdmin)
admin:
    resource: ../src/Controller/Admin/DashboardController.php
    type: attribute
    prefix: /admin

# Routes de sécurité
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Routes principales
app_home:
    path: /
    controller: App\Controller\HomeController::index

app_livre_index:
    path: /livre
    controller: App\Controller\LivreController::index

app_livre_show:
    path: /livre/{id}
    controller: App\Controller\LivreController::show
