# Configuration de production pour les routes
# Ce fichier définit les routes de l'application

# Routes d'administration (EasyAdmin)
easy_admin:
    resource: ../src/Controller/Admin/DashboardController.php
    type: attribute
    prefix: /admin

# Routes de sécurité
security:
    resource: ../src/Controller/SecurityController.php
    type: attribute
    prefix: /

# Routes d'enregistrement
registration:
    resource: ../src/Controller/RegistrationController.php
    type: attribute
    prefix: /

# Routes principales
home:
    resource: ../src/Controller/HomeController.php
    type: attribute
    prefix: /

livre:
    resource: ../src/Controller/LivreController.php
    type: attribute
    prefix: /
