framework:
    default_locale: fr
    translator:
        # Configuration de production pour la traduction
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
