twig_component:
    # Configuration de production pour les composants Twig
    anonymous_template_directory: '%kernel.project_dir%/templates/components'
    
    # Configuration du cache des composants
    cache:
        enabled: true
        type: 'cache.adapter.filesystem'
        namespace: 'twig_components'
