# Configuration principale des services
# Ce fichier définit la configuration de base des services

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Chargement automatique des contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Chargement automatique des entités
    App\Entity\:
        resource: '../src/Entity/'

    # Chargement automatique des repositories
    App\Repository\:
        resource: '../src/Repository/'

    # Chargement automatique des commandes
    App\Command\:
        resource: '../src/Command/'
        tags: ['console.command']
